### ISSUE TITLE
Building on Windows first time errors out during linking

### ISSUE THREAD

**Issue by Miladiir** [BernardoGiordano/EventAssistant#1]
... and then again when building the smdh and 3dsx file.
This is caused by ./EventAssistant and ./EventAssistant/3ds/EventAssistant/ not being created.

Check for their existence and create them if necessary.

**Comment by BernardoGiordano** [comment]
hello! this is simple, makefile wants to save in those folder (who help me save LOTS of time in packing the releases, as it basically put in order the file). Maybe i have to delete 'latest' folder to pickup the latest commits build and add the folders used in the makefile to store them. In this way, if you try to compile it by yourself it will work first time
