### ISSUE TITLE
Set all TM's option removes the dive HM from ORAS

### ISSUE THREAD

**Issue by Kurolox** [BernardoGiordano/EventAssistant#13]
The option "Set all TM's" seems to give you all the TM's (From TM1 to TM100) and all HM's from HM01 to HM06. It doesn't give you the HM07 Dive though, and if you had it, it will be removed.

**Comment by BernardoGiordano** [comment]
good to know, will check asap.

**Comment by BernardoGiordano** [comment]
[Fixed](https://github.com/BernardoGiordano/EventAssistant/compare/2.3.0...master), closing
