### ISSUE TITLE
Gen IV wondercard flag not set correctly

### ISSUE THREAD

**Issue by BernardoGiordano** [BernardoGiordano/EventAssistant#17]
There's something weird in [this line](https://github.com/BernardoGiordano/EventAssistant/blob/master/source/pokemon.c#L565)

**Comment by kwsch** [comment]
Gen 4 stores two save files; I don't think having a [const offset](https://github.com/BernardoGiordano/EventAssistant/blob/master/source/pokemon.c#L42) would work as intended. Gotta detect which save file is active based on the incremental Counters in the footer to get the actual offset!

Also, be careful to not set a flag with a value higher than the bitflag array length. Eon Ticket (2048) is 0x800, which would overflow into Card 1's ID. Not really a problem, but if users have a hacked card with an invalid ID it'd toggle a bit beyond the intended range :)

**Comment by BernardoGiordano** [comment]
Good to know!! Thanks so much, you're really awesome

**Comment by BernardoGiordano** [comment]
[Made a few modifications](https://github.com/BernardoGiordano/EventAssistant/commit/3516237071ea89b52aa32317457d9e0bcd10b761) basing upon PKHeX source. Does general block and storage block have to be calculated every time I do an operation, or only at save loading? I'm currently calculating it only at save loading and passing these values to every function that needs them, but still no modifications appear in game

**Comment by BernardoGiordano** [comment]
![immagine](https://cloud.githubusercontent.com/assets/17624378/18416189/fa3a90c8-780c-11e6-9e61-1ecc57d03d04.png)
EDIT: Modifications made on Pearl worked, PKHeX recognizes them. It did not work for HG, but since it worked on Pearl, and the algorhitm is the same, I presume it's only a corrupted save of mine. Will leave this open until more testes are done
