### ISSUE TITLE
Pokemon Alpha Sapphire doesn't work

### ISSUE THREAD

**Issue by CodyMKW** [BernardoGiordano/EventAssistant#21]
when I select Event Assistant or any other homebrew app with the eshop version of Alpha Sapphire it freezes on a greenish yellow looking screen

**Comment by BernardoGiordano** [comment]
Just retry.

**Comment by CodyMKW** [comment]
I been trying a lot same thing everytime

**Comment by BernardoGiordano** [comment]
It's a problem with your homebrew setup certainly. Could you share your setup + firmware?

**Comment by CodyMKW** [comment]
I'm running 11.1.0.34U using steelhax heres the root of the sd card and the 3ds folder 
http://i.imgur.com/SWfwSKG.png
http://i.imgur.com/UVucicT.png

**Comment by BernardoGiordano** [comment]
And you're selecting correctly Alpha Sapphire in the prompt, right?

**Comment by CodyMKW** [comment]
yes

**Comment by CodyMKW** [comment]
I'm guessing [this is the problem](https://gbatemp.net/threads/release-jks-savemanager-homebrew-cia-save-manager.413143/page-97#post-6686288) to this issue
