### ISSUE TITLE
Help wanted: new 3D banner needed

### ISSUE THREAD

**Issue by BernardoGiordano** [BernardoGiordano/EventAssistant#27]
I'm looking for someone that knows how to make 3D banners. If you know someone, address him there

**Comment by Akawashi** [comment]
i'll ask the guys on 3dschaos... we have working S/M leaks, maybe it could help u develop ur app... PkHex has already made some basic progress. if u have the games, im sure you could make compatible with s&m :)
as for the banner, i'm sure i know someone who can help... (i can make banner pic and audio, but i dunno hoe to make image, ... yet ;)

**Comment by BernardoGiordano** [comment]
I don't need any leak. I'll test my progresses only after my physical cart will arrive, I ordered them. I'm already adapting my code, game is not really needed right now, I'll test everything after 11/18.

If you know someone good at making 3D banner just put him in contact with me!

**Comment by Akawashi** [comment]
ok, check us out wen u have time: www.3dschaos.com (changing url due to site merger soon.)
we convert whole anime to moflexto inject to 3ds.
because of that, i can make banner.bin & icon.bin.
i'll ask around now.

**Comment by Akawashi** [comment]
![image](https://cloud.githubusercontent.com/assets/18169962/20318597/bd4c6d88-ab62-11e6-9bd6-c6a0b8f525c4.png)

**Comment by Akawashi** [comment]
also, if u want, i can test before 11/18.

**Comment by BernardoGiordano** [comment]
Done by myself using freeware only

**Comment by Akawashi** [comment]
Nice to hear, cant wait to see the new changes, this is probably the best homebrew app for pokemon!
btw, would it be possible to edit rom saves from a flashcart i.e. R4i3ds?
