### ISSUE TITLE
Says No internet connection when there is..

### ISSUE THREAD

**Issue by proflayton123** [BernardoGiordano/EventAssistant#4]
Hi!~

Great app btw, when I try to use it though it says no internet connection available although i tested and everything was fine, is there a fix for this? Am I missing something? Downloaded the .cia version. :)

**Comment by proflayton123** [comment]
it happens when ever i try to do any of the options, would you like me to take some pictures? :)

**Comment by BernardoGiordano** [comment]
yes, tell me also which version and if you're using it on hbl or cfw. a few of you managed to have this error, but it everytime 'solved automatically' restarting the app or something. This error never showed uo to me, then i really don't know which could be the issue

**Comment by BernardoGiordano** [comment]
no answers, closing
