### ISSUE TITLE
Add N's pokemon to the collections.

### ISSUE THREAD

**Issue by poutros** [BernardoGiordano/EventAssistant#7]
The pokemon all have a static pid so it's easy to check whether they're legit or not. Either way, I've included them in the zip because I don't know how I would go about making a pr and make those bin files.
They are all unevolved and untrained but have my own trainer as latest trainer (obviously since I transfered them). Everything besides pokebank transfer stuff remains unaltered. They are as legit as I can have them (since pokebank alters/adds a few stuff).

[n's pokemon.zip](https://github.com/BernardoGiordano/EventAssistant/files/452043/n.s.pokemon.zip)

**Comment by BernardoGiordano** [comment]
I will add them asap. Thank for attaching them!

**Comment by BernardoGiordano** [comment]
feature added, closing
